version: '3.7'

services:
  web_dev:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - ${PORT_DEV}:8000
    env_file:
      - ./.env.dev
    networks:
      - dev
    depends_on:
      - db_dev

  db_dev:
    image: postgres:12.0-alpine
    volumes:
        - postgres_data_dev:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=shopping_cart
        - POSTGRES_PASSWORD=shopping_cart
        - POSTGRES_DB=shopping_cart_dev
    networks:
      - dev
    
volumes:
    postgres_data_dev:

networks:
    dev:
      driver: bridge
