# Generated by Django 3.0.7 on 2020-08-15 20:40

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200815_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to='', validators=[apps.product.models.validate_file_extension], verbose_name='Imagen'),
        ),
    ]
