# Generated by Django 3.0.7 on 2020-08-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0, null=True, verbose_name='Total')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
            ],
        ),
    ]
